#!/bin/bash

# To be submitted as a qsub array job
# Requires a text file with filepaths to process, one path per line
# E.g. qsub -t 1-$(cat filestoprocess.txt | wc -l) visiomode-generate-regressors.array.sh filestoprocess.txt
# The file filestoprocess.txt should contain paths to the timestamp files generated by mesoscopy-extract-timestamps.sh, one path per line

#$ -N visiomode-generate-regressors

#$ -l h_rt=00:30:00
#$ -l h_rss=4G

#$ -hold_jid stagein

#$ -m eas
#$ -M Constantinos.Eleftheriou@ed.ac.uk

#$ -o logs/visiomode-generate-regressors_$JOB_ID.log
#$ -e logs/visiomode-generate-regressors_$JOB_ID.errors
PATH="$PATH:~/.local/bin/"
OUTBOX="/exports/eddie/scratch/$USER/outbox"

# SGE_TASK_ID will go from 1 to the number of files when we submit an array job
F=`sed -n ${SGE_TASK_ID}p < $1`

visiomode-analysis session --with-regressors --regressor-timestamps "${F}" --output-dir "$OUTBOX" "${F/_meso*_timestamps.txt/.json}"